apps/api/src/intern/dto/createIntern.dto.ts
apps/api/src/intern/intern.controller.ts
apps/api/src/intern/intern.service.ts
apps/web/src/api/useSetInterview.ts
apps/web/src/components/InputHandler/InputHandler.tsx
apps/web/src/components/InternList/InternList.tsx
apps/web/src/components/IntervieweeInfo/IntervieweeInfo.tsx
apps/web/src/constants/interviewConstants.ts
apps/web/src/pages/ApplicationFormPage/ApplicationFormPage.tsx
apps/web/src/pages/ApplicationFormPage/constants/ApplicationFormQuestions.ts
apps/web/src/pages/InterviewPage/InterviewPage.tsx
apps/web/src/pages/InterviewPage/data.ts
packages/types/src/interview.ts

Connected interview with backend - fetching intern data and saving answers.
Also, improved logic for registering interns.

Interview connect

---

apps/api/src/intern/intern.controller.ts
apps/api/src/intern/intern.service.ts
apps/web/src/api/useApplyBoardAction.ts
apps/web/src/api/useApplyInternAction.ts
apps/web/src/components/Actions/Actions.tsx
apps/web/src/components/BoardActions/BoardActions.tsx
apps/web/src/components/BoardActions/options.ts
apps/web/src/components/InternActions/InternActions.tsx
apps/web/src/components/InternActions/options.ts
apps/web/src/pages/DashboardPage/DashboardPage.tsx
apps/web/src/pages/InternInfoPage/InternInfoPage.tsx
packages/types/src/action.ts

Added actions for intern, currently for adding/removing disciplines.

Intern actions

---

apps/web/src/api/useApplyBoardAction.ts
apps/web/src/api/useApplyInternAction.ts
apps/web/src/api/useCreateEmails.tsx
apps/web/src/api/usePostIntern.tsx
apps/web/src/api/useScheduleInterview.ts
apps/web/src/api/useSendEmails.ts
apps/web/src/api/useSetInternDecision.ts
apps/web/src/api/useSetInterview.ts
apps/web/src/pages/ScheduleInterviewPage/ScheduleInterviewPage.tsx

application-form toast and redirect... and remove all mutationKeys

---

apps/api/src/intern/intern.service.ts
apps/web/src/components/InternInfo/InternInfo.tsx
apps/web/src/components/InternInfo/index.module.css
apps/web/src/components/IntervieweeInfo/IntervieweeInfo.tsx
apps/web/src/components/IntervieweeInfo/index.module.css

Josipa saravanja/candidate info changes

---

apps/api/src/intern/intern.controller.ts
apps/api/src/interview-slot/interview-slot.controller.ts
apps/api/src/interviewer/interviewer.controller.ts
apps/api/src/test-slot/test-slot.controller.ts
apps/web/src/api/useFetchAvailableTestSlots.tsx

add auth guards

---

apps/api/prisma/seed.ts
apps/web/src/components/InternList/InternList.tsx

Added yearOfBirth column to `InternList` ( closes #108  )

InternList - Year of birth

---

apps/web/src/components/SortableDiscipline.tsx

fixing sorting of disciplines on touch screens

---

apps/api/src/interview-slot/interview-slot.controller.ts
apps/api/src/interview-slot/interview-slot.service.ts
apps/web/src/api/useFetchSlotsAvailability.tsx
apps/web/src/components/SlotsList/SlotsList.tsx
apps/web/src/components/SlotsList/index.ts
apps/web/src/pages/AdminInterviewPage/AdminInterviewPage.tsx
apps/web/src/pages/AdminInterviewPage/index.module.css
apps/web/src/pages/DashboardPage/DashboardPage.tsx
packages/types/src/intern.ts
packages/types/src/interview.ts

admin: interview slots availability

---

apps/api/src/interview-slot/interview-slot.service.ts
apps/api/src/test-slot/test-slot.service.ts
apps/web/src/api/useScheduleInterview.ts
apps/web/src/api/useScheduleTest.ts
apps/web/src/components/InternList/InternList.tsx
apps/web/src/pages/ScheduleInterviewPage/ScheduleInterviewPage.tsx
apps/web/src/pages/ScheduleTestPage/ScheduleTestPage.tsx
packages/types/src/test.ts

Interview and test can be scheduled 24hrs / 10mins before the actual slot.
If an error is thrown while scheduling, slots are prefetched.

Fixing slot scheduling

---

apps/web/src/components/EmailPreviewList/EmailPreviewList.tsx
apps/web/src/pages/EmailPage/EmailPage.tsx

fixed small bugs

---

apps/api/src/interview-slot/interview-slot.service.ts
apps/web/src/api/useScheduleInterview.ts
apps/web/src/api/useScheduleTest.ts
apps/web/src/pages/StatusPage/StatusPage.tsx
apps/web/src/pages/StatusPage/styled.ts

... and interview schedule-before-actual time reduced to 12hrs.

Choose slot on status page

---

apps/web/src/pages/AdminInterviewPage/AdminInterviewPage.tsx
apps/web/src/pages/ApplicationFormPage/constants/ApplicationFormQuestions.ts
apps/web/src/pages/StatusPage/StatusPage.tsx
packages/types/src/intern.ts

Fixing interview scheduler 2hrs delay

Interview date fix

---

apps/api/prisma/seed.ts
apps/web/src/components/InternFilter/InternFilter.tsx
apps/web/src/pages/DashboardPage/DashboardPage.module.css
apps/web/src/pages/DashboardPage/DashboardPage.tsx

Duplicates table

---

apps/web/src/components/InternFilter/InternFilter.tsx
apps/web/src/components/InternFilter/filter.ts
apps/web/src/components/InternList/InternList.tsx
apps/web/src/pages/TestChoosePage/TestChoosePage.tsx
apps/web/src/pages/TestPage/TestPage.tsx
packages/types/src/intern.ts

New bugfixes/features:
- intern can write one test question in multiple languages without losing progress
- language is inherited from last one until it's dirty
- interview pts sort is fixed
- enabled filter by email and test id

Bugfixing: test & dashboard

---

apps/api/src/intern/intern.service.ts
apps/web/src/pages/StatusPage/DisciplineCard.tsx
apps/web/src/pages/StatusPage/styled.ts
packages/types/src/intern.ts

adding test questions scores to status page

---

apps/web/src/pages/DashboardPage/DashboardPage.tsx

changed duplicated table logic
- now displays all duplicate interns without checking the status
- trims name and surname strings
- comparison is case-insensitive

duplicates table logic fix

---

apps/api/src/intern/intern.service.ts
apps/api/src/interviewer/interviewer.service.ts
apps/web/src/api/useFetchAllInterns.tsx
apps/web/src/api/useFetchAllInterviewers.tsx
apps/web/src/components/InternFilter/filter.ts
apps/web/src/components/InternList/InternList.tsx
apps/web/src/pages/InterviewersPage/InterviewersPage.tsx
packages/types/src/intern.ts

Added 2 columns to dashboard that are hidden by default:
- log count
- registration date
Added average score to interviewer.

Dashboard new cols, average interviewer score

---

apps/web/src/pages/InterviewPage/data.ts

Popis pitanja [https://docs.google.com/document/d/1CbrAmfJZxiZ8evWpyFD286VOoBbHJvDa_RULpdKE7Mo/edit](url)

Updated interview questions

---

apps/api/src/intern/intern.service.ts

Added condition for Marketing discipline emails and added a google forms link

Marketing signup email

---

apps/api/src/intern/intern.service.ts

I saw you approved and just merged without noticing the comment, I shortened them.

shortened links

---

apps/api/src/prisma.service.ts

closes #229 
za zatvaranje aktivnih konekcija

add onModuleDestroy

---

apps/api/src/app.module.ts
apps/web/src/components/InternFilter/InternFilter.tsx
apps/web/src/components/InternFilter/filter.ts
apps/web/src/pages/DashboardPage/DashboardPage.tsx
apps/web/src/pages/DashboardPage/helpers.ts
packages/types/src/intern.ts

main i discipline filteri se persistaju u query parametrima i loadaju se na refresh stranice.

228 fix interns filtering
